export const EVENT_CREATION_SUCCESS = "EVENT_CREATION_SUCCESS"
export const EVENT_CREATION_ERROR = "EVENT_CREATION_ERROR"

export const GET_EVENT_LIST_PAGE_SUCCESS = "GET_EVENT_LIST_PAGE_SUCCESS"
export const GET_EVENT_LIST_PAGE_ERROR = "GET_EVENT_LIST_PAGE_ERROR"