export const EVENT_CREATION_SUCCESS = "EVENT_CREATION_SUCCESS"
export const EVENT_CREATION_ERROR = "EVENT_CREATION_ERROR"

export const GET_EVENT_LIST_PAGE_BY_ACCOUNT_SUCCESS = "GET_EVENT_LIST_PAGE_BY_ACCOUNT_SUCCESS"
export const GET_EVENT_LIST_PAGE_BY_ACCOUNT_ERROR = "GET_EVENT_LIST_PAGE_BY_ACCOUNT_ERROR"