export const GET_CHAT_PAGE_SUCCESS = "GET_CHAT_PAGE_SUCCESS"
export const GET_CHAT_PAGE_ERROR = "GET_CHAT_PAGE_ERROR"

export const OPEN_UPDATE_CHAT = "OPEN_UPDATE_CHAT"
export const CLOSE_UPDATE_CHAT = "CLOSE_UPDATE_CHAT"

export const FETCH_MORE_CHATS_SUCCESS = "FETCH_MORE_CHATS_SUCCESS"
export const FETCH_MORE_CHATS_ERROR = "FETCH_MORE_CHATS_ERROR"