export const ROOM_CREATION_SUCCESS = "ROOM_CREATION_SUCCESS"
export const ROOM_CREATION_ERROR = "ROOM_CREATION_ERROR"

export const ROOM_DELETION_SUCCESS = "ROOM_DELETION_SUCCESS"
export const ROOM_DELETION_ERROR = "ROOM_DELETION_ERROR"

export const GET_ROOM_LIST_PAGE_SUCCESS = "GET_ROOM_LIST_PAGE_SUCCESS"
export const GET_ROOM_LIST_PAGE_ERROR = "GET_ROOM_LIST_PAGE_ERROR"