export const ROOM_CREATION_SUCCESS = "ROOM_CREATION_SUCCESS"
export const ROOM_CREATION_ERROR = "ROOM_CREATION_ERROR"

export const ROOM_DELETION_SUCCESS = "ROOM_DELETION_SUCCESS"
export const ROOM_DELETION_ERROR = "ROOM_DELETION_ERROR"

export const GET_ROOM_LIST_PAGE_SUCCESS = "GET_ROOM_LIST_PAGE_SUCCESS"
export const GET_ROOM_LIST_PAGE_ERROR = "GET_ROOM_LIST_PAGE_ERROR"

export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS"
export const UPDATE_ROOM_ERROR = "UPDATE_ROOM_ERROR"

export const OPEN_UPDATE_ROOM = "OPEN_UPDATE_ROOM"
export const CLOSE_UPDATE_ROOM = "CLOSE_UPDATE_ROOM"

export const FETCH_MORE_ROOMS_SUCCESS = "FETCH_MORE_ROOMS_SUCCESS"
export const FETCH_MORE_ROOMS_ERROR = "FETCH_MORE_ROOMS_ERROR"