export const SINGLE_ROOM_FOUND = "SINGLE_ROOM_FOUND"
export const SET_CURRENT_USERNAME = "SET_CURRENT_USERNAME"
export const OPEN_CREATE_GUEST = "OPEN_CREATE_GUEST"
export const CLOSE_CREATE_GUEST = "CLOSE_CREATE_GUEST"