export const GET_ROOM_LIST_PAGE_SUCCESS = "GET_ROOM_LIST_PAGE_SUCCESS"
export const GET_ROOM_LIST_PAGE_ERROR = "GET_ROOM_LIST_PAGE_ERROR"

export const OPEN_UPDATE_ROOM = "OPEN_UPDATE_ROOM"
export const CLOSE_UPDATE_ROOM = "CLOSE_UPDATE_ROOM"

export const FETCH_MORE_ROOMS_SUCCESS = "FETCH_MORE_ROOMS_SUCCESS"
export const FETCH_MORE_ROOMS_ERROR = "FETCH_MORE_ROOMS_ERROR"