export const MEETING_CREATION_SUCCESS = "MEETING_CREATION_SUCCESS"
export const MEETING_CREATION_ERROR = "MEETING_CREATION_ERROR"

export const GET_MEETING_LIST_PAGE_SUCCESS = "GET_MEETING_LIST_PAGE_SUCCESS"
export const GET_MEETING_LIST_PAGE_ERROR = "GET_MEETING_LIST_PAGE_ERROR"